//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManager.CPMail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://caseparts.com/webservices/", ConfigurationName="CPMail.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name mailFrom from namespace http://caseparts.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://caseparts.com/webservices/Email", ReplyAction="*")]
        ContactManager.CPMail.EmailResponse Email(ContactManager.CPMail.EmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://caseparts.com/webservices/Email", ReplyAction="*")]
        System.Threading.Tasks.Task<ContactManager.CPMail.EmailResponse> EmailAsync(ContactManager.CPMail.EmailRequest request);
        
        // CODEGEN: Generating message contract since element name listCode from namespace http://caseparts.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://caseparts.com/webservices/EmailList", ReplyAction="*")]
        ContactManager.CPMail.EmailListResponse EmailList(ContactManager.CPMail.EmailListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://caseparts.com/webservices/EmailList", ReplyAction="*")]
        System.Threading.Tasks.Task<ContactManager.CPMail.EmailListResponse> EmailListAsync(ContactManager.CPMail.EmailListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Email", Namespace="http://caseparts.com/webservices/", Order=0)]
        public ContactManager.CPMail.EmailRequestBody Body;
        
        public EmailRequest() {
        }
        
        public EmailRequest(ContactManager.CPMail.EmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://caseparts.com/webservices/")]
    public partial class EmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mailFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mailTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isBodyHtml;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bcc;
        
        public EmailRequestBody() {
        }
        
        public EmailRequestBody(string mailFrom, string mailTo, string subject, string body, bool isBodyHtml, string cc, string bcc) {
            this.mailFrom = mailFrom;
            this.mailTo = mailTo;
            this.subject = subject;
            this.body = body;
            this.isBodyHtml = isBodyHtml;
            this.cc = cc;
            this.bcc = bcc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailResponse", Namespace="http://caseparts.com/webservices/", Order=0)]
        public ContactManager.CPMail.EmailResponseBody Body;
        
        public EmailResponse() {
        }
        
        public EmailResponse(ContactManager.CPMail.EmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmailResponseBody {
        
        public EmailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailList", Namespace="http://caseparts.com/webservices/", Order=0)]
        public ContactManager.CPMail.EmailListRequestBody Body;
        
        public EmailListRequest() {
        }
        
        public EmailListRequest(ContactManager.CPMail.EmailListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://caseparts.com/webservices/")]
    public partial class EmailListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string listCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mailFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string body;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isBodyHtml;
        
        public EmailListRequestBody() {
        }
        
        public EmailListRequestBody(string listCode, string mailFrom, string subject, string body, bool isBodyHtml) {
            this.listCode = listCode;
            this.mailFrom = mailFrom;
            this.subject = subject;
            this.body = body;
            this.isBodyHtml = isBodyHtml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EmailListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EmailListResponse", Namespace="http://caseparts.com/webservices/", Order=0)]
        public ContactManager.CPMail.EmailListResponseBody Body;
        
        public EmailListResponse() {
        }
        
        public EmailListResponse(ContactManager.CPMail.EmailListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EmailListResponseBody {
        
        public EmailListResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ContactManager.CPMail.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ContactManager.CPMail.ServiceSoap>, ContactManager.CPMail.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ContactManager.CPMail.EmailResponse ContactManager.CPMail.ServiceSoap.Email(ContactManager.CPMail.EmailRequest request) {
            return base.Channel.Email(request);
        }
        
        public void Email(string mailFrom, string mailTo, string subject, string body, bool isBodyHtml, string cc, string bcc) {
            ContactManager.CPMail.EmailRequest inValue = new ContactManager.CPMail.EmailRequest();
            inValue.Body = new ContactManager.CPMail.EmailRequestBody();
            inValue.Body.mailFrom = mailFrom;
            inValue.Body.mailTo = mailTo;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.isBodyHtml = isBodyHtml;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            ContactManager.CPMail.EmailResponse retVal = ((ContactManager.CPMail.ServiceSoap)(this)).Email(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ContactManager.CPMail.EmailResponse> ContactManager.CPMail.ServiceSoap.EmailAsync(ContactManager.CPMail.EmailRequest request) {
            return base.Channel.EmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ContactManager.CPMail.EmailResponse> EmailAsync(string mailFrom, string mailTo, string subject, string body, bool isBodyHtml, string cc, string bcc) {
            ContactManager.CPMail.EmailRequest inValue = new ContactManager.CPMail.EmailRequest();
            inValue.Body = new ContactManager.CPMail.EmailRequestBody();
            inValue.Body.mailFrom = mailFrom;
            inValue.Body.mailTo = mailTo;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.isBodyHtml = isBodyHtml;
            inValue.Body.cc = cc;
            inValue.Body.bcc = bcc;
            return ((ContactManager.CPMail.ServiceSoap)(this)).EmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ContactManager.CPMail.EmailListResponse ContactManager.CPMail.ServiceSoap.EmailList(ContactManager.CPMail.EmailListRequest request) {
            return base.Channel.EmailList(request);
        }
        
        public void EmailList(string listCode, string mailFrom, string subject, string body, bool isBodyHtml) {
            ContactManager.CPMail.EmailListRequest inValue = new ContactManager.CPMail.EmailListRequest();
            inValue.Body = new ContactManager.CPMail.EmailListRequestBody();
            inValue.Body.listCode = listCode;
            inValue.Body.mailFrom = mailFrom;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.isBodyHtml = isBodyHtml;
            ContactManager.CPMail.EmailListResponse retVal = ((ContactManager.CPMail.ServiceSoap)(this)).EmailList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ContactManager.CPMail.EmailListResponse> ContactManager.CPMail.ServiceSoap.EmailListAsync(ContactManager.CPMail.EmailListRequest request) {
            return base.Channel.EmailListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ContactManager.CPMail.EmailListResponse> EmailListAsync(string listCode, string mailFrom, string subject, string body, bool isBodyHtml) {
            ContactManager.CPMail.EmailListRequest inValue = new ContactManager.CPMail.EmailListRequest();
            inValue.Body = new ContactManager.CPMail.EmailListRequestBody();
            inValue.Body.listCode = listCode;
            inValue.Body.mailFrom = mailFrom;
            inValue.Body.subject = subject;
            inValue.Body.body = body;
            inValue.Body.isBodyHtml = isBodyHtml;
            return ((ContactManager.CPMail.ServiceSoap)(this)).EmailListAsync(inValue);
        }
    }
}
